Все готово кроме комментов
AleksanderYandexPracticum/java-shareit pull request #5
Opened 2023-08-21 15:32 UTC by AleksanderYandexPracticum

Все готово кроме комментов

Остались комментарии

Все готово

Все готово

Все готово

Все готово

Все готово

2023-08-22 15:26 UTC, kalitva requested changes

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingServiceImpl bookingServiceImpl;
`BookingServiceImpl --> BookingService`
Храни по типу интерфейса

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Строка параметров запроса: '{}'",
Логируй только по английски, иначе могут быть проблемы с кодировкой

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @RequestHeader("X-Sharer-User-Id") Long owner,
Давай вынесем `X-Sharer-User-Id` в константу

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Data
Лучше используй вместо `@Data` 
```java
@Getter
@Setter
```
Иначе могут быть проблемы

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private User booker;  //пользователь, который осуществляет бронирование
Не думаю, что эти комменты нужны, они поясняют очевидные вещи

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public BookingDto(Long id, LocalDateTime start, LocalDateTime end, Item item, User booker, Status status) {
Используй `@AllArgsConstructor` ломбока

https://projectlombok.org/features/constructor

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>      // WAITING — новое бронирование, ожидает одобрения
Удали эти комменты

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userRepository.findUserById(owner) == null) {
Используй `user.existsById` для проверки наличия записи в БД

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (itemRepository.findItemById(itemId) == null) {
То же самое, поправь все подобные кейсы

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        validationAvailable(requestBookingDto.getItemId()); // проверка доступности для бронирования
Все методы валидации переименуй по шаблону `validation... --> validate...`, название метода это всегда глагол или глагольное словосочетание

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals("WAITING")) {
Наверное. имеется в виду `eilse if`

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemAndLastAndNextBookingDto.java
> +    private String description; //развёрнутое описание
Поудаляй все эти комменты

2023-08-22 15:26 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "created", nullable = false)
`name`  можно не указывать если имя поля в БД совпадает с именем поля ентити

2023-08-22 15:26 UTC, kalitva commented on src/main/resources/schema.sql
> +-- Таблица с пользователями
Эти все комменты также не нужны

2023-08-22 15:56 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingServiceImpl bookingServiceImpl;
Исправил во всех контроллерах

2023-08-22 16:01 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private User booker;  //пользователь, который осуществляет бронирование
Удалил

2023-08-22 16:02 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/dto/ItemAndLastAndNextBookingDto.java
> +    private String description; //развёрнутое описание
Удалил

2023-08-22 16:02 UTC, AleksanderYandexPracticum commented on src/main/resources/schema.sql
> +-- Таблица с пользователями
Удалил

2023-08-22 16:07 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Column(name = "created", nullable = false)
Исправил

2023-08-22 16:08 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>      // WAITING — новое бронирование, ожидает одобрения
Удалил

2023-08-22 16:16 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        validationAvailable(requestBookingDto.getItemId()); // проверка доступности для бронирования
Исправил

2023-08-22 16:18 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals("WAITING")) {
Сделал

2023-08-22 16:56 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info("Получен запрос к эндпоинту: '{} {}', Строка параметров запроса: '{}'",
Сделал

2023-08-22 17:14 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public BookingDto(Long id, LocalDateTime start, LocalDateTime end, Item item, User booker, Status status) {
Исправил

2023-08-22 17:15 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Data
Сделал

2023-08-22 17:35 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (itemRepository.findItemById(itemId) == null) {
Сделал

2023-08-22 17:36 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userRepository.findUserById(owner) == null) {
Сделал

2023-08-22 18:00 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @RequestHeader("X-Sharer-User-Id") Long owner,
Вынес, только зачем это надо не пойму?

2023-08-22 18:02 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Это рекомендация или требование?  В ТЗ не было ограничений на использование методов

2023-08-23 15:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @RequestHeader("X-Sharer-User-Id") Long owner,
Погугли на тему "Магические числа", вот например https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования

2023-08-23 15:18 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Рекомендация, но советую ей последовать)

2023-08-23 15:34 UTC, kalitva requested changes

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingService bookingServiceImpl;
`bookingServiceImpl --> bookingService`

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @PathVariable("bookingId") Long bookingId,
`@PathVariable Long bookingId,`
Спринг распознает имя переменной пути по имени параметра

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(Item item, User user, RequestBookingDto requestBookingDto, Status status) {
Мы можем каким-либо образом уменьшить число параметров метода?

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingNewNameIdDto.java
> +import lombok.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking(LocalDateTime start, LocalDateTime end, Item item, User booker, Status status) {
Конструктор всегда объявляется перед полями

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateAvailable(Long itemId) {
Приватные метода обычно объявляются после публичных

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +@EqualsAndHashCode
Нам разве  нужны `equals` и `toString` для дтошек? Предлагаю добавлять это все по мере необходимости

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemAndLastAndNextBookingDto.java
> +    public ItemAndLastAndNextBookingDto(Long id, String name, String description, Boolean available,
Давай для моделей, конструкторы которых принимают больше 3х параметров использовать `@Builder` ломбока

https://projectlombok.org/features/Builder

Ломбок реализует паттерн билдер, погугли немного чтобы иметь представление что это и зачем, например
https://www.digitalocean.com/community/tutorials/builder-design-pattern-in-java

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  @Service("ItemServiceImpl")
Нам точно нужно определять имя бина?

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item != null) {  //Это если не владелец вещи
Коммент вводит в заблуждение

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      }
Давай обойдемся без промежуточной переменной

```java
        try {
            return UserMapper.toUserDto(userRepository.getById(id));
        } catch (EntityNotFoundException e) {
            log.info(String.format("There is no user with an ID  № %s", id));
            throw new NotFoundException(String.format("There is no user with an ID  № %s", id));
        }
```

2023-08-23 15:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            validateEmailforUpdate(id, userDto);
Поправь опечатку `validateEmailForUpdate`

2023-08-23 15:52 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingService bookingServiceImpl;
Исправил

2023-08-23 15:55 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            validateEmailforUpdate(id, userDto);
Исправил

2023-08-23 15:58 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      }
Исправил

2023-08-23 15:59 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item != null) {  //Это если не владелец вещи
Удалил

2023-08-23 16:03 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking(LocalDateTime start, LocalDateTime end, Item item, User booker, Status status) {
Сделал

2023-08-23 16:13 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/dto/BookingNewNameIdDto.java
> +import lombok.*;
Сделал

2023-08-23 16:14 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  @Service("ItemServiceImpl")
Я бы хотел оставить, чтобы потом не переделывать если понадобится, это же не критично?

2023-08-23 16:18 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void validateAvailable(Long itemId) {
Перенес методы

2023-08-23 16:23 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +@EqualsAndHashCode
Удалил

2023-08-23 18:06 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/dto/ItemAndLastAndNextBookingDto.java
> +    public ItemAndLastAndNextBookingDto(Long id, String name, String description, Boolean available,
Сделал

2023-08-23 18:07 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toBooking(Item item, User user, RequestBookingDto requestBookingDto, Status status) {
нет

2023-08-23 18:10 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @PathVariable("bookingId") Long bookingId,
Сделал

2023-08-23 19:25 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @RequestHeader("X-Sharer-User-Id") Long owner,
Сделал

2023-08-23 19:58 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Сделал один метод, получилось громоздко и не читаемо.
Может в других случаях и оправдано,  но тут нет), одной строчкой проще читать

2023-08-24 15:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  @Service("ItemServiceImpl")
Нет, удали, поставишь обратно если понадобится

2023-08-24 15:46 UTC, kalitva approved these changes

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Не, не то, в этом интерфейсе вообще не должно было остаться методов

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
`X_SHARER_USER_ID --> USER_ID_HEADER`

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>      public static Item toItem(Long owner, ItemDto itemDto) {
Лучше обойтись без статических методов и инжектить мапперы спрингом

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@AllArgsConstructor
Где-то используется этот конструктор? Если нет, удали (касается всех подобных кейсов)

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +
Удали лишние пустые линии

2023-08-24 15:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else if (itemDto.getDescription() == null || itemDto.getDescription().isBlank()) {
Здесь не нужны `else`, исключение прерывает выполнение метода

2023-08-24 16:18 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +
Удалил

2023-08-24 16:35 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@AllArgsConstructor
Удалил

2023-08-24 16:39 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String X_SHARER_USER_ID = "X-Sharer-User-Id";
Сделал

2023-08-24 16:41 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else if (itemDto.getDescription() == null || itemDto.getDescription().isBlank()) {
Исправил

2023-08-24 16:46 UTC, AleksanderYandexPracticum commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  @Service("ItemServiceImpl")
Хорошо, удалил

2023-08-24 16:54 UTC, merged